GET http://localhost:4000/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvYW5nQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJob2FuZ25tIiwiaWF0IjoxNjA4NTM4MjAzfQ.KbUSU4KyoovdiyOrzr4A953Y8U_eRbXDSebx1GvnpDw

###

GET http://localhost:4000/rooms/1

###
